CC = gcc
CFLAGS = -Wall -Wextra
EXECUTABLES = ex1 ex2 ex3 ex4 ex5 ex6 ex7

#all: $(EXECUTABLES)

ex7: ex7.c

ex6: ex6.c

ex5: ex5.c

ex4: ex4.c

ex3: ex3.c

ex2: ex2.c

ex1: ex1.c

clean:
	rm -f $(EXECUTABLES)
